const IconPath='../Assests/Icons/'
export const Home=require(IconPath+'home.png')
export const Call=require(IconPath+'call.png')
export const User=require(IconPath+'user.png')
export const User1=require(IconPath+'user1.png')
export const Mail=require(IconPath+'mail.png')
export const Pen=require(IconPath+'pen.png')
export const Lock=require(IconPath+'lock2.png')
export const Exit=require(IconPath+'exit.png')
